name: full

on:
  push:
    branches: [ multiarch ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: arm64,arm
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2-build-push
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./tags/alpine/Dockerfile
          platforms: linux/arm/v6,linux/arm/v7,linux/arm64
          push: false
          tags: victorrds/etesync:alpine