---
name: MultiArch

on:
  push:
    branches: [ multiarch ]

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      ES_TAG: master

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          repository: etesync/server
          path: server
          ref: ${{ env.ES_TAG }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: amd64,arm64,arm
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      -
        name: Login to DockerHub
        uses: docker/login-action@v1.3.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2-build-push
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./tags/alpine/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
          push: true
          tags: victorrds/etesync:experimental-alpine