name: Build Debian based image on Pull Requests

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'context/**'
      - 'tags/base/Dockerfile'
      - '.github/workflows/*-base.yml'

jobs:
  build-base:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: pavulonx/etebase-server
          always_pull: true
          add_git_labels: true
          push: false
          dockerfile: ./tags/base/Dockerfile
          tags: ${{ github.sha }}
          build_args: REPO_REF=master