name: Build Debian based image master

on:
  push:
    branches: [ master ]
    paths:
      - 'context/**'
      - 'tags/debian/Dockerfile'
      - '.github/workflows/*-debian.yml'

jobs:
  build-debian:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: pavulonx/etebase-server
          always_pull: true
          add_git_labels: true
          push: false
          dockerfile: ./tags/debian/Dockerfile
          tags: ${{ github.sha }}-debian
          build_args: REPO_REF=master