name: Build Alpine Tag on Pull Requests

on:
  push:
    branches: [ master ]
    paths:
      - 'entrypoint.sh'
      - 'config_templates/**'
      - 'tags/alpine/Dockerfile'
      - '.github/workflows/*-alpine.yml'

jobs:
  build-alpine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: pavulonx/etebase-server
          always_pull: true
          add_git_labels: true
          push: false
          dockerfile: ./tags/alpine/Dockerfile
          tags: ${{ github.sha }}-alpine
          build_args: TAG=${{ github.sha }}