name: Release images

on:
  push:
    tags:
      - 'v*'

jobs:
  build-alpine-master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: pavulonx/etebase-server
          always_pull: true
          add_git_labels: true
          push: true
          dockerfile: ./tags/alpine/Dockerfile
          tags: master-alpine
          build_args: REPO_REF=master

  build-alpine-v0-5-0:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: pavulonx/etebase-server
          always_pull: true
          add_git_labels: true
          push: true
          dockerfile: ./tags/alpine/Dockerfile
          tags: 0.5.0-alpine, alpine
          build_args: REPO_REF=v0.5.0

  build-base-master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: pavulonx/etebase-server
          always_pull: true
          add_git_labels: true
          push: true
          dockerfile: ./tags/base/Dockerfile
          tags: master
          build_args: REPO_REF=master

  build-base-v0-5-0:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: pavulonx/etebase-server
          always_pull: true
          add_git_labels: true
          push: true
          dockerfile: ./tags/base/Dockerfile
          tags: 0.5.0, latest
          build_args: REPO_REF=v0.5.0

      - uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Release version of docker images ${{ github.ref }}
          draft: false
          prerelease: false