name: Build and Push Alpine Tags

on:
  push:
    branches: [ release ]
    paths:
      - 'entrypoint.sh'
      - 'config_templates/**'
      - 'tags/alpine/Dockerfile'
      - '.github/workflows/release-alpine.yml'
jobs:
  build-master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'release'
      - uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: pavulonx/etebase-server
          always_pull: true
          add_git_labels: true
          push: true
          dockerfile: ./tags/debian/Dockerfile
          tags: alpine
          build_args: TAG=master

  build-v030:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'release'
      - uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: pavulonx/etebase-server
          always_pull: true
          add_git_labels: true
          push: true
          dockerfile: ./tags/debian/Dockerfile
          tags: 0.3.0-alpine
          build_args: TAG=v0.3.0