name: Build and Push Alpine based image

on:
  push:
    branches: [ release ]
    paths:
      - 'entrypoint.sh'
      - 'config_templates/**'
      - 'tags/alpine/Dockerfile'
      - '.github/workflows/release-alpine.yml'
jobs:
  build-alpine-master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'release'
      - uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: pavulonx/etebase-server
          always_pull: true
          add_git_labels: true
          push: true
          dockerfile: ./tags/alpine/Dockerfile
          tags: master-alpine, master
          build_args: REPO_REF=master

  build-alpine-v0.5.0:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'release'
      - uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: pavulonx/etebase-server
          always_pull: true
          add_git_labels: true
          push: true
          dockerfile: ./tags/alpine/Dockerfile
          tags: 0.5.0-alpine, 0.5.0, latest
          build_args: REPO_REF=v0.5.0