name: Release images

on:
  push:
    tags:
      - 'v*'

jobs:
  build-alpine-master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: pavulonx/etebase-server
          always_pull: true
          add_git_labels: true
          push: true
          dockerfile: ./tags/alpine/Dockerfile
          tags: master-alpine, master
          build_args: REPO_REF=master

  build-alpine-v0-5-0:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: pavulonx/etebase-server
          always_pull: true
          add_git_labels: true
          push: true
          dockerfile: ./tags/alpine/Dockerfile
          tags: 0.5.0-alpine, 0.5.0, alpine, latest
          build_args: REPO_REF=v0.5.0

      - uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Release version of docker images ${{ github.ref }}
          draft: false
          prerelease: false

  build-debian-master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'release'
      - uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: pavulonx/etebase-server
          always_pull: true
          add_git_labels: true
          push: true
          dockerfile: ./tags/debian/Dockerfile
          tags: master-debian
          build_args: REPO_REF=master

  build-debian-v0-5-0:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'release'
      - uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: pavulonx/etebase-server
          always_pull: true
          add_git_labels: true
          push: true
          dockerfile: ./tags/debian/Dockerfile
          tags: 0.5.0-debian, debian
          build_args: REPO_REF=v0.5.0